let root='', currentFile=''; const $=s=>document.querySelector(s);
const views={home:`<div class="view"><div class="hero"><span class="badge">FORGEMIND AI 0.1</span><h2>Build. Model. Create.</h2><p>A desktop development workstation for coding, 3D workflows and controlled automation. ForgeMind is designed around explicit permissions so you stay in control of Roblox Studio and Blender.</p><button class="primary" style="width:auto;padding:12px 20px" onclick="openProject()">Open a project</button></div><div class="grid"><div class="card"><span class="badge">CODE</span><h3>Code Lab</h3><p>Project-aware editing with AI assistance and multi-language workflows.</p></div><div class="card"><span class="badge">3D</span><h3>Blender Bridge</h3><p>Connect Blender only after you grant permission. Actions are designed to be reviewable.</p></div><div class="card"><span class="badge">GAME DEV</span><h3>Roblox Bridge</h3><p>Prepare Studio automation through a permissioned local bridge.</p></div></div></div>`,
code:`<div class="view"><div class="editor"><div class="files"><b>PROJECT</b><div id="fileList" class="muted" style="margin-top:10px">Open a project to browse files.</div></div><div class="code"><div class="toolbar" id="fileName">No file selected</div><textarea id="editor" class="codearea" spellcheck="false" placeholder="Open a project, then choose a file..."></textarea><div class="toolbar"><button onclick="saveFile()" style="background:none;border:0;color:#9db3ff">Save Ctrl+S</button></div></div></div></div>`,
ai:`<div class="view"><div class="chat"><div class="chatbox"><div class="messages" id="messages"><div class="msg"><b>ForgeMind</b><br>I'm ready. Ask me to explain code, design a system, create a script, or plan a 3D workflow.</div></div><div class="prompt"><input id="prompt" placeholder="Ask ForgeMind anything about your project..." onkeydown="if(event.key==='Enter')sendPrompt()"><button onclick="sendPrompt()">Send</button></div></div><div class="permission"><h3>AI Cloud Mode</h3><p class="muted">This build deliberately requires <b>no API key</b>. The app is prepared for a hosted ForgeMind gateway, while keeping secrets out of the desktop client.</p><div class="toggle"><span>Cloud assistant</span><span class="switch on"></span></div><div class="keybox">No personal API key stored in this application.</div><p class="muted">A real public cloud AI still needs a service running somewhere. This client cannot create or pay for that service by itself.</p></div></div></div>`,
bridge:`<div class="view"><div class="hero"><span class="badge">PERMISSION CENTER</span><h2>Studio Bridges</h2><p>ForgeMind never silently takes control of other applications. Each bridge is isolated and can be enabled independently.</p></div><div class="grid"><div class="card"><h3>🎮 Roblox Studio</h3><p>Controlled bridge for approved Studio operations.</p><div class="toggle"><span>Allow bridge</span><span class="switch" onclick="this.classList.toggle('on')"></span></div><div class="toggle"><span>Read project</span><span class="switch" onclick="this.classList.toggle('on')"></span></div><div class="toggle"><span>Write changes</span><span class="switch" onclick="this.classList.toggle('on')"></span></div></div><div class="card"><h3>🧊 Blender</h3><p>Controlled bridge for scene and modelling workflows.</p><div class="toggle"><span>Allow bridge</span><span class="switch" onclick="this.classList.toggle('on')"></span></div><div class="toggle"><span>Read scene</span><span class="switch" onclick="this.classList.toggle('on')"></span></div><div class="toggle"><span>Run approved scripts</span><span class="switch" onclick="this.classList.toggle('on')"></span></div></div><div class="card"><h3>🔐 Action approval</h3><p>Recommended for anything that changes files, scenes or projects.</p><div class="toggle"><span>Confirm changes</span><span class="switch on" onclick="this.classList.toggle('on')"></span></div><p class="success">Protection enabled</p></div></div></div>`,
settings:`<div class="view"><div class="card"><h2>ForgeMind Settings</h2><div class="settingrow"><b>Cloud architecture</b><small>No API keys are required by the client.</small></div><div class="settingrow"><b>Installation mode</b><small>Designed as a standalone desktop application.</small></div><div class="settingrow"><b>Privacy</b><small>Local project files are accessed only through explicit desktop permissions.</small></div><div class="settingrow"><b>Distribution</b><small>GitHub can distribute the installer, but a public link alone is not an access-control system.</small></div></div></div>`};
function render(v){$('#content').innerHTML=views[v];$('#title').textContent={home:'Workspace',code:'Code Lab',ai:'ForgeMind AI',bridge:'Studio Bridges',settings:'Settings'}[v];if(v==='code'&&root)loadFiles();}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view)});async function openProject(){root=await forge.pickFolder();if(root){render('code')}}window.openProject=openProject;$('#projectBtn').onclick=openProject;
async function loadFiles(){const items=await forge.listFiles(root);const el=$('#fileList');el.innerHTML='';items.filter(x=>!x.dir).slice(0,100).forEach(x=>{const d=document.createElement('div');d.className='file';d.textContent='📄 '+x.name;d.onclick=async()=>{currentFile=root+'\\'+x.name;$('#fileName').textContent=x.name;$('#editor').value=(await forge.readFile(currentFile))||''};el.appendChild(d)});items.filter(x=>x.dir).forEach(x=>{const d=document.createElement('div');d.className='file';d.textContent='📁 '+x.name;el.appendChild(d)})}
async function saveFile(){if(currentFile){const ok=await forge.writeFile(currentFile,$('#editor').value);$('#fileName').textContent=ok?'Saved ✓':'Save failed';}}window.saveFile=saveFile;document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='s'){e.preventDefault();saveFile()}});
function sendPrompt(){const i=$('#prompt'),t=i.value.trim();if(!t)return;const m=$('#messages');m.innerHTML+=`<div class="msg you">${esc(t)}</div><div class="msg"><b>ForgeMind</b><br>Cloud AI gateway is the next connection layer. This client is ready for a keyless hosted gateway, but no third-party API key is embedded here.</div>`;i.value='';m.scrollTop=m.scrollHeight}function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
render('home');
