let root='', currentFile='', activeView='home';
const $=s=>document.querySelector(s);
const state=JSON.parse(localStorage.getItem('forgemind-settings')||'{}');
const views={
home:`<div class="view"><div class="hero"><span class="badge">FORGEMIND AI 0.2</span><h2>Build. Model. Create.</h2><p>Your AI development workstation for coding, game development and 3D creation. Open a workspace, connect approved tools and let ForgeMind help you build.</p><div class="actions"><button class="primary" onclick="openProject()">＋ Open Project</button><button class="secondary" onclick="show('ai')">✦ Ask ForgeMind</button></div></div><div class="grid"><div class="card stat"><b>CODE LAB</b><strong>Multi-language</strong><span>Project-aware editing</span></div><div class="card stat"><b>ROBLOX</b><strong id="robloxState">Disconnected</strong><span>Permission controlled</span></div><div class="card stat"><b>BLENDER</b><strong id="blenderState">Disconnected</strong><span>Permission controlled</span></div></div><div class="card"><h3>Quick start</h3><div class="quick"><button onclick="openProject()">Open workspace</button><button onclick="show('code')">Open Code Lab</button><button onclick="show('bridge')">Configure bridges</button><button onclick="show('ai')">Start AI chat</button></div></div></div>`,
code:`<div class="view"><div class="editor"><div class="files"><div class="filehead"><b>PROJECT</b><button onclick="refreshFiles()">↻</button></div><div id="projectPath" class="muted tiny">No workspace selected</div><div id="fileList" class="filetree muted">Open a project to browse files.</div><div class="fileactions"><button onclick="newFile()">＋ File</button><button onclick="newFolder()">＋ Folder</button></div></div><div class="code"><div class="toolbar"><span id="fileName">No file selected</span><span id="saveState" class="muted">Ready</span></div><textarea id="editor" class="codearea" spellcheck="false" placeholder="Choose a file from your project..."></textarea><div class="toolbar bottom"><button onclick="saveFile()">Save</button><button onclick="formatHint()">AI format</button><span class="muted">Ctrl+S</span></div></div></div></div>`,
ai:`<div class="view"><div class="chat"><div class="chatbox"><div class="messages" id="messages"><div class="msg"><b>ForgeMind</b><br>Ready. Tell me what you want to build, debug, script or model.</div></div><div class="prompt"><input id="prompt" placeholder="Ask ForgeMind about your project..." onkeydown="if(event.key==='Enter')sendPrompt()"><button onclick="sendPrompt()">Send</button></div></div><div class="card ai-side"><h3>AI Workspace</h3><p class="muted">Cloud mode is keyless on the desktop client. When the ForgeMind cloud gateway is connected, requests can be routed there without storing a personal API key.</p><div class="settingrow"><b>Project context</b><small id="contextState">No project selected</small></div><div class="settingrow"><b>Action safety</b><small>Changes require approval when enabled.</small></div><label class="switchrow"><span>Require approval</span><button class="switch ${state.confirm!==false?'on':''}" data-key="confirm" onclick="toggleSetting(this)"></button></label></div></div></div>`,
bridge:`<div class="view"><div class="hero compact"><span class="badge">PERMISSION CENTER</span><h2>Connected tools</h2><p>Each integration is independent. A switch changes the stored permission immediately and updates the status.</p></div><div class="grid"><div class="card"><h3>🎮 Roblox Studio</h3><p class="muted">Allow ForgeMind to communicate with an approved local Studio bridge.</p>${switchRow('Roblox bridge','roblox',false)}${switchRow('Read project','robloxRead',false)}${switchRow('Write changes','robloxWrite',false)}<div id="robloxStatus" class="statusline">● Disconnected</div></div><div class="card"><h3>🧊 Blender</h3><p class="muted">Allow ForgeMind to communicate with an approved local Blender bridge.</p>${switchRow('Blender bridge','blender',false)}${switchRow('Read scene','blenderRead',false)}${switchRow('Run approved scripts','blenderWrite',false)}<div id="blenderStatus" class="statusline">● Disconnected</div></div><div class="card"><h3>🔐 Safety</h3><p class="muted">Keep this enabled if you want ForgeMind to ask before modifying projects.</p>${switchRow('Confirm changes','confirm',true)}${switchRow('Allow destructive actions','destructive',false)}<div class="warning">Destructive actions should stay disabled unless you specifically need them.</div></div></div></div>`,
settings:`<div class="view"><div class="card"><h2>ForgeMind Settings</h2><div class="settingrow"><b>Cloud mode</b><small>Desktop client stores no personal AI API key.</small></div><div class="settingrow"><b>Installed mode</b><small>ForgeMind is designed to run as a standalone desktop application.</small></div><div class="settingrow"><b>Workspace</b><small id="settingsProject">No workspace selected</small></div><div class="settingrow"><b>Access</b><small>This local build can be distributed from GitHub. A GitHub link alone cannot enforce owner-only access; use authentication/invites for that.</small></div><button class="secondary" onclick="resetSettings()">Reset permissions</button></div></div>`};
function switchRow(label,key,on){return `<label class="switchrow"><span>${label}</span><button class="switch ${state[key]!==undefined?state[key]?'on':'':on?'on':''}" data-key="${key}" onclick="toggleSetting(this)"></button></label>`}
function saveState(){localStorage.setItem('forgemind-settings',JSON.stringify(state))}
function toggleSetting(el){const k=el.dataset.key;state[k]=!state[k];el.classList.toggle('on',state[k]);saveState();updateStatuses()}
function updateStatuses(){const rb=!!state.roblox, bl=!!state.blender; ['robloxState','robloxStatus'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=rb?'● Bridge permission enabled':'● Disconnected'});['blenderState','blenderStatus'].forEach(id=>{const e=$('#'+id);if(e)e.textContent=bl?'● Bridge permission enabled':'● Disconnected'})}
function show(v){activeView=v;document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#content').innerHTML=views[v];$('#title').textContent={home:'Workspace',code:'Code Lab',ai:'ForgeMind AI',bridge:'Studio Bridges',settings:'Settings'}[v];if(v==='code')loadFiles();if(v==='ai'){$('#contextState').textContent=root||'No project selected'}if(v==='settings')$('#settingsProject').textContent=root||'No workspace selected';updateStatuses()}
async function openProject(){const r=await forge.pickFolder();if(r){root=r;show('code')}}
async function refreshFiles(){if(root)loadFiles()}
async function loadFiles(){const el=$('#fileList');if(!el)return;$('#projectPath').textContent=root;el.innerHTML='';const items=await forge.listFiles(root);items.forEach(x=>{const d=document.createElement('button');d.className='file';d.textContent=(x.dir?'📁 ':'📄 ')+x.name;d.onclick=()=>x.dir?openFolder(x.path):selectFile(x.path,x.name);el.appendChild(d)})}
function openFolder(p){root=p;loadFiles()}
async function selectFile(p,name){currentFile=p;$('#fileName').textContent=name;$('#saveState').textContent='Loaded';$('#editor').value=(await forge.readFile(p))??''}
async function saveFile(){if(!currentFile){return}const ok=await forge.writeFile(currentFile,$('#editor').value);$('#saveState').textContent=ok?'Saved ✓':'Save failed'}
async function newFile(){if(!root)return;const name=prompt('New file name','script.lua');if(!name)return;const ok=await forge.createFile(root+'\\'+name,'');if(ok)loadFiles()}
async function newFolder(){if(!root)return;const name=prompt('New folder name','NewFolder');if(!name)return;const ok=await forge.makeFolder(root+'\\'+name);if(ok)loadFiles()}
function formatHint(){if(!$('#editor'))return;$('#saveState').textContent='AI formatting request ready'}
function sendPrompt(){const i=$('#prompt'),t=i?.value.trim();if(!t)return;const m=$('#messages');m.innerHTML+=`<div class="msg you">${esc(t)}</div><div class="msg"><b>ForgeMind</b><br>I received your request. The desktop client is ready for the cloud gateway; no personal API key is stored here. I can also work with your local project once you grant the relevant permissions.</div>`;i.value='';m.scrollTop=m.scrollHeight}
function esc(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function resetSettings(){if(confirm('Reset all integration permissions?')){Object.keys(state).forEach(k=>delete state[k]);saveState();show('bridge')}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.view));$('#projectBtn').onclick=openProject;document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();saveFile()}});show('home');
window.openProject=openProject;window.show=show;window.refreshFiles=refreshFiles;window.newFile=newFile;window.newFolder=newFolder;window.selectFile=selectFile;window.saveFile=saveFile;window.formatHint=formatHint;window.sendPrompt=sendPrompt;window.toggleSetting=toggleSetting;window.resetSettings=resetSettings;
