if (!window.forge) { document.body.innerHTML='<div style="font-family:Segoe UI;padding:40px;color:white;background:#090b12;height:100vh"><h1>ForgeMind could not start</h1><p>The desktop bridge is unavailable. Restart the app.</p></div>'; throw new Error('preload bridge unavailable'); }
let S,currentFile='';
const $=id=>document.getElementById(id);
const pages=['home','forge','code','projects','roblox','blender','account','settings'];
function go(page){pages.forEach(p=>{const el=$('page-'+p);if(el)el.classList.toggle('hidden',p!==page)});document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('crumb').textContent=({home:'Chat',forge:'Create',code:'Code',projects:'Projects',roblox:'Roblox',blender:'Blender',account:'Identity',settings:'Settings'})[page]||page;}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
async function refresh(){S=await window.forge.getState();$('provider').value=S.ai.provider||'Lemonade';$('baseUrl').value=S.ai.baseUrl||'http://127.0.0.1:13305/v1';$('model').value=S.ai.model||'';$('email').value=S.identity.email||'';$('displayName').value=S.identity.displayName||'';$('robloxUserId').value=S.identity.robloxUserId||'';$('keyStatus').textContent=S.hasApiKey?'API key stored securely.':'No API key saved — local Lemonade usually needs none.';document.querySelectorAll('[data-perm]').forEach(x=>x.checked=!!S.permissions[x.dataset.perm]);setStatus('Bridge: 127.0.0.1:'+S.bridgePort,true);await detectModels(true);}
function setStatus(text,ok){$('bridgeStatus').textContent=text;$('statusDot').classList.toggle('ok',!!ok)}
async function savePerm(k,v){S.permissions[k]=v;await window.forge.setState({permissions:S.permissions});}
document.querySelectorAll('[data-perm]').forEach(x=>x.onchange=()=>savePerm(x.dataset.perm,x.checked));
async function detectModels(silent=false){const base=($('baseUrl').value||'').trim().replace(/\/+$/,'');const select=$('chatModel');if(!base)return;try{const r=await window.forge.listModels(base);const models=(r?.data||[]).map(x=>x.id).filter(Boolean);select.innerHTML='<option value="">Auto</option>'+models.map(m=>`<option value="${escapeHtml(m)}">${escapeHtml(m)}</option>`).join('');if(S.ai?.model)select.value=S.ai.model;else if(models.length){select.value=models[0];$('model').value=models[0];await window.forge.setState({ai:{...S.ai,model:models[0]}})}if(!silent)setStatus(models.length?`${models.length} model${models.length===1?'':'s'} available`:'Server reachable, no models found',true);return models;}catch(e){if(!silent)setStatus('AI server not reachable',false);return[]}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
$('saveAI').onclick=async()=>{await window.forge.setState({ai:{provider:$('provider').value.trim(),baseUrl:$('baseUrl').value.trim(),model:$('model').value.trim()}});if($('apiKey').value.trim())await window.forge.setApiKey($('apiKey').value.trim());$('apiKey').value='';await refresh()};
$('clearKey').onclick=async()=>{await window.forge.clearApiKey();await refresh()};
$('detectModels').onclick=()=>detectModels(false);
$('chatModel').onchange=async()=>{if($('chatModel').value){$('model').value=$('chatModel').value;await window.forge.setState({ai:{...S.ai,model:$('chatModel').value}})}};
$('saveIdentity').onclick=async()=>{await window.forge.setState({identity:{...S.identity,email:$('email').value.trim(),displayName:$('displayName').value.trim()}});await refresh()};
$('saveRoblox').onclick=async()=>{await window.forge.setState({identity:{...S.identity,robloxUserId:$('robloxUserId').value.trim()}});await refresh()};
function addChat(text,who){$('emptyChat')?.remove();const d=document.createElement('div');d.className='msg '+who;d.textContent=text;$('chat').appendChild(d);$('chat').scrollTop=$('chat').scrollHeight;return d}
async function sendChat(){const t=$('chatInput').value.trim();if(!t)return;$('chatInput').value='';addChat(t,'user');const loading=addChat('Thinking…','ai');loading.classList.add('spinner');try{const model=$('chatModel').value||$('model').value.trim();const messages=[{role:'system',content:'You are ForgeMind AI, a concise and practical desktop assistant. Help with coding, game development, 3D assets, Roblox Studio and Blender. Give actionable steps. Do not claim an external action happened unless the app actually performed it.'},{role:'user',content:t}];const r=await window.forge.chat(messages,model);loading.textContent=r;loading.classList.remove('spinner');setStatus(model?'Connected • '+model:'Connected',true)}catch(e){loading.textContent='Could not reach the AI. '+e.message;loading.classList.remove('spinner');setStatus('AI server not reachable',false)}}
$('sendChat').onclick=sendChat;$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();sendChat()}});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('chatInput').value=b.dataset.prompt;$('chatInput').focus()});
$('forgeAsset').onclick=()=>{const p=$('assetPrompt').value.trim()||'Untitled asset';$('assetTitle').textContent=p.slice(0,80);$('assetMeta').textContent=`${$('assetType').value} • ${$('assetPlatform').value} • ${$('assetStyle').value} • ${$('assetQuality').value}`;$('assetTags').innerHTML=['Prompted','Reference-aware','Game-ready',$('assetPlatform').value].map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('')};
$('sendAssetAI').onclick=()=>{go('home');$('chatInput').value=`Create a better, production-ready brief for this asset: ${$('assetPrompt').value||'a game-ready asset'}`;$('chatInput').focus()};
async function bridge(target,command,permission='action'){try{await window.forge.bridgeCommand({target,permission,...command});logBridge(target,JSON.stringify(command));}catch(e){logBridge(target,'Blocked: '+e.message,true)}}
function logBridge(target,text,bad=false){const id=target==='roblox'?'robloxLog':'blenderLog';const d=document.createElement('div');d.className='row';d.innerHTML=`<span>${escapeHtml(text)}</span><span class="small">${bad?'blocked':'queued'}</span>`;$(id).prepend(d)}
$('robloxPing').onclick=()=>bridge('roblox',{type:'ping'});$('robloxPart').onclick=()=>bridge('roblox',{type:'create_part',name:'ForgeMind_TestPart',size:[4,2,4],position:[0,5,0],anchored:true});$('blenderPing').onclick=()=>bridge('blender',{type:'ping'});$('blenderCube').onclick=()=>bridge('blender',{type:'create_cube',name:'ForgeMind_TestCube',location:[0,0,0],scale:[1,1,1]});
$('chooseFile').onclick=async()=>{const p=await window.forge.chooseFile();if(!p)return;currentFile=p;$('filePath').textContent=p;$('editor').value=await window.forge.readFile(p)};
$('saveFile').onclick=async()=>{if(!currentFile)return alert('Open a file first.');await window.forge.writeFile(currentFile,$('editor').value);$('filePath').textContent=currentFile+' • saved'};
$('askCode').onclick=()=>{go('home');$('chatInput').value='Review and improve this code. Explain the important changes first, then provide the corrected code:\n\n'+$('editor').value.slice(0,12000);$('chatInput').focus()};
$('chooseProject').onclick=async()=>{const p=await window.forge.chooseFolder();if(p){$('projectPath').textContent=p;loadFiles(p);go('projects')}};$('projectFolder').onclick=async()=>{const p=await window.forge.chooseFolder();if(p){$('projectPath').textContent=p;loadFiles(p)}};
async function loadFiles(p){const list=await window.forge.listFiles(p);$('fileList').innerHTML='';list.slice(0,300).forEach(f=>{const d=document.createElement('div');d.className='row';const name=document.createElement('span');name.textContent=(f.isDir?'📁 ':'📄 ')+f.name;d.appendChild(name);if(!f.isDir){const b=document.createElement('button');b.className='btn small';b.textContent='Open';b.onclick=async()=>{currentFile=f.path;$('filePath').textContent=f.path;$('editor').value=await window.forge.readFile(f.path);go('code')};d.appendChild(b)}$('fileList').appendChild(d)})}
window.forge.onBridgeResult(v=>logBridge(v.target,JSON.stringify(v.value)));window.forge.onBridgeStatus(v=>setStatus(v.ok?'Local bridge ready':'Bridge error: '+(v.error||''),!!v.ok));
refresh();
